### ISSUE TITLE
Exception Thrown on Startup

### ISSUE THREAD

**Issue by DavidJSGardner** [polserver/UOFiddler#106]
When you launch fiddler and click the load profile button in the initial menu that appears an exception is thrown IF you do not have a connection to the internet. There are on occasion, times when I need to launch fiddler but do not have an internet connection available (technically I can hotspot my phone of course but would rather not as it is a bit of a hassle to do if I am not doing anything web related on my laptop.)

This is the exception I get if it helps hunt anything down to allow fiddler to run without an internet connection.

```
Unable to connect to the remote server
System.Net.WebException

An error occurred while sending the request.

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Internal.HttpClientAdapter.<SendAsync>d__10.MoveNext() in /home/runner/work/octokit.net/octokit.net/Octokit/Http/HttpClientAdapter.cs:line 195
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Internal.HttpClientAdapter.<Send>d__3.MoveNext() in /home/runner/work/octokit.net/octokit.net/Octokit/Http/HttpClientAdapter.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<RunRequest>d__61.MoveNext() in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 679
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.Connection.<Run>d__60`1.MoveNext() in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 670
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<Get>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UoFiddler.Classes.UpdateChecker.<CheckUpdateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UoFiddler.Classes.UpdateRunner.<RunAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at UoFiddler.FiddlerAppContext..ctor(ILogger logger)
   at UoFiddler.Program.Main()
 ```

**Comment by AsYlum-** [comment]
Thanks. As a workaround you can just turn off automatic update checks until this is resolved. Help -> About -> uncheck "Check On Start"
![image](https://user-images.githubusercontent.com/377468/201903217-f08f6e5c-da91-4d87-9759-142010130c21.png)

**Comment by AsYlum-** [comment]
Fixed in: https://github.com/polserver/UOFiddler/releases/tag/4.9.19
