### ISSUE TITLE
Bug report - unhandled exception.

### ISSUE THREAD

**Issue by Admin-Yukiko** [polserver/UOFiddler#107]
I tried to change the path settings to a different client folder and Fiddler threw an exception. So I closed it and re-opened Fiddler now I get this exception. I deleted everything inside my Fiddler folder and copied the contents of the Fiddler zip file to my Fiddler folder and that did not resolve the issue. This happens with versions 4.9.8, 4.9.10, 4.9.16, and 4.9.17.  So I have reverted to 4.9.6
```
System.TypeInitializationException: The type initializer for 'Ultima.Textures' threw an exception. ---> System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Ultima Online\texidx.mul' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Ultima.FileIndex..ctor(String idxFile, String mulFile, String uopFile, Int32 length, Int32 file, String uopEntryExtension, Int32 idxLength, Boolean hasExtra)
   at Ultima.FileIndex..ctor(String idxFile, String mulFile, Int32 length, Int32 file)
   at Ultima.Textures..cctor()
   --- End of inner exception stack trace ---
   at Ultima.Textures.TestTexture(Int32 index)
   at UoFiddler.Controls.UserControls.TexturesControl.UpdateLabels(Int32 graphic)
   at UoFiddler.Controls.UserControls.TexturesControl.set_SelectedTextureId(Int32 value)
   at UoFiddler.Forms.MainForm.InitializeComponent()
   at UoFiddler.Forms.MainForm..ctor()
   at UoFiddler.FiddlerAppContext..ctor(ILogger logger)
   at UoFiddler.Program.Main()
```

**Comment by AsYlum-** [comment]
From exception seems like file was blocked by some other process/application. I'll close this for now as I have no idea what can be done here. File path and access improvements are planned and on my todo list already.
