### ISSUE TITLE
Gumps, Dress, Cliloc, Radarcol issues with latest OSI update

### ISSUE THREAD

**Issue by GladieUO** [polserver/UOFiddler#123]
These tabs cannot be opened with the newest OSI update.

```
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at Ultima.Gumps.GetGump(Int32 index, Boolean& patched)
   at Ultima.Gumps.GetGump(Int32 index)
   at UoFiddler.Controls.UserControls.GumpControl.ListBox_SelectedIndexChanged(Object sender, EventArgs e)
   at UoFiddler.Controls.UserControls.GumpControl.PopulateListBox(Boolean showOnlyValid)
   at UoFiddler.Controls.UserControls.GumpControl.OnLoad(EventArgs e)
   at UoFiddler.Controls.UserControls.GumpControl.HasGumpId(Int32 gumpId)
   at UoFiddler.Controls.UserControls.ItemsControl.TileViewContextMenuStrip_Opening(Object sender, CancelEventArgs e)
   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ContextMenuStrip.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ToolStripDropDown.Show(Control control, Point position)
   at System.Windows.Forms.Control.WmContextMenu(Message& m, Control sourceControl)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```
```
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at Ultima.Gumps.GetGump(Int32 index, Boolean& patched)
   at UoFiddler.Controls.UserControls.GumpControl.ListBox_DrawItem(Object sender, DrawItemEventArgs e)
   at System.Windows.Forms.ListBox.WmReflectDrawItem(Message& m)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```
```
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at Ultima.Gumps.GetGump(Int32 index, Boolean& patched)
   at Ultima.Gumps.GetGump(Int32 index)
   at UoFiddler.Controls.UserControls.DressControl.DrawPaperdoll()
   at UoFiddler.Controls.UserControls.DressControl.OnLoad(Object sender, EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.TabControl.UpdateTabSelection(Boolean updateFocus)
   at System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```
```
System.ArgumentOutOfRangeException: count ('-32173') must be a non-negative value. (Parameter 'count')
Actual value was -32173.
   at System.ArgumentOutOfRangeException.ThrowNegative[T](T value, String paramName)
   at Ultima.StringList.LoadEntry(String path)
   at Ultima.StringList..ctor(String language)
   at UoFiddler.Controls.UserControls.ClilocControl.set_Lang(Int32 value)
   at UoFiddler.Controls.UserControls.ClilocControl.OnLoad(Object sender, EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.TabControl.UpdateTabSelection(Boolean updateFocus)
   at System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

**Comment by AsYlum-** [comment]
Latest update for new legacy beta 7.104.0 has new gump format and encrypted clilocs. Right now I have idea when it will work. So last version that uofiddler can work with is 7.103.0

**Comment by CantFindDev** [comment]
RIP

**Comment by AsYlum-** [comment]
@GladieUO partial support for compressed clilocs was added in https://github.com/polserver/UOFiddler/releases/tag/4.15.2 Rest is still work in progress.

**Comment by AsYlum-** [comment]
@GladieUO @CantFindDev  you can now read the NL compressed gumps if you upgrade to latest version https://github.com/polserver/UOFiddler/releases/tag/4.16.1
