### ISSUE TITLE
Can't open Cliloc with new patch

### ISSUE THREAD

**Issue by craymaru** [polserver/UOFiddler#124]
After updating the UO Client, I can no longer open Cliloc.

```
Just-In-Time (JIT) デバッグを呼び出すための詳細については、
ダイアログ ボックスではなく、このメッセージの最後を参照してください。

************** 例外テキスト **************
System.ArgumentOutOfRangeException: count ('-32173') must be a non-negative value. (Parameter 'count')
Actual value was -32173.
   at System.ArgumentOutOfRangeException.ThrowNegative[T](T value, String paramName)
   at Ultima.StringList.LoadEntry(String path)
   at Ultima.StringList..ctor(String language)
   at UoFiddler.Controls.UserControls.ClilocControl.set_Lang(Int32 value)
   at UoFiddler.Controls.UserControls.ClilocControl.OnLoad(Object sender, EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.TabControl.UpdateTabSelection(Boolean updateFocus)
   at System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)


************** 読み込まれたアセンブリ **************
System.Private.CoreLib
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Private.CoreLib.dll
----------------------------------------
UoFiddler
    アセンブリ バージョン: 4.15.1.0
    場所: C:\ServUO\Tools\UOFiddler\UoFiddler.dll
----------------------------------------
System.Runtime
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Runtime.dll
----------------------------------------
Serilog
    アセンブリ バージョン: 4.0.0.0
    場所: C:\ServUO\Tools\UOFiddler\Serilog.dll
----------------------------------------
Serilog.Sinks.File
    アセンブリ バージョン: 6.0.0.0
    場所: C:\ServUO\Tools\UOFiddler\Serilog.Sinks.File.dll
----------------------------------------
System.Text.Encoding.CodePages
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Text.Encoding.CodePages.dll
----------------------------------------
System.Windows.Forms
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.7\System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.7\System.Windows.Forms.Primitives.dll
----------------------------------------
System.Drawing.Primitives
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Collections.Specialized.dll
----------------------------------------
System.Collections
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Collections.dll
----------------------------------------
System.Linq
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Linq.dll
----------------------------------------
System.Text.RegularExpressions
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Text.RegularExpressions.dll
----------------------------------------
System.Memory
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Memory.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Threading
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Threading.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Primitives
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Reflection.Primitives.dll
----------------------------------------
System.Private.Uri
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Private.Uri.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Diagnostics.Tracing
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Diagnostics.Tracing.dll
----------------------------------------
System.Text.Encoding.Extensions
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Text.Encoding.Extensions.dll
----------------------------------------
Controls
    アセンブリ バージョン: 4.4.0.0
    場所: C:\ServUO\Tools\UOFiddler\Controls.dll
----------------------------------------
System.Drawing.Common
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.7\System.Drawing.Common.dll
----------------------------------------
System.Runtime.InteropServices
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Runtime.InteropServices.dll
----------------------------------------
System.Diagnostics.TraceSource
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Diagnostics.TraceSource.dll
----------------------------------------
Microsoft.Win32.Primitives
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Threading.Thread.dll
----------------------------------------
Accessibility
    アセンブリ バージョン: 4.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.7\Accessibility.dll
----------------------------------------
System.Numerics.Vectors
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Numerics.Vectors.dll
----------------------------------------
System.ComponentModel.TypeConverter
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ComponentModel
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.ComponentModel.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.7\Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.ObjectModel
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.ObjectModel.dll
----------------------------------------
System.Collections.NonGeneric
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Collections.NonGeneric.dll
----------------------------------------
System.Xml.ReaderWriter
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Private.Xml.dll
----------------------------------------
Ultima
    アセンブリ バージョン: 4.3.2.0
    場所: C:\ServUO\Tools\UOFiddler\Ultima.dll
----------------------------------------
Microsoft.Win32.Registry
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\Microsoft.Win32.Registry.dll
----------------------------------------
System.Diagnostics.Process
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Diagnostics.Process.dll
----------------------------------------
Octokit
    アセンブリ バージョン: 13.0.1.0
    場所: C:\ServUO\Tools\UOFiddler\Octokit.dll
----------------------------------------
netstandard
    アセンブリ バージョン: 2.1.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\netstandard.dll
----------------------------------------
System.Net.Http
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Net.Primitives.dll
----------------------------------------
System.Net.Security
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Net.Security.dll
----------------------------------------
System.Security.Cryptography
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Security.Cryptography.dll
----------------------------------------
System.Collections.Concurrent
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Collections.Concurrent.dll
----------------------------------------
System.Net.Sockets
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Net.Sockets.dll
----------------------------------------
System.Threading.Overlapped
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Threading.Overlapped.dll
----------------------------------------
System.Net.NameResolution
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Net.NameResolution.dll
----------------------------------------
System.Threading.ThreadPool
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Threading.ThreadPool.dll
----------------------------------------
System.Runtime.Intrinsics
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Runtime.Intrinsics.dll
----------------------------------------
System.Security.Principal.Windows
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Security.Claims.dll
----------------------------------------
System.Linq.Expressions
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Linq.Expressions.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    アセンブリ バージョン: 0.0.0.0
    場所: 
----------------------------------------
System.IO.Compression
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.IO.Compression.dll
----------------------------------------
System.Runtime.Loader
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.7\ja\System.Windows.Forms.resources.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Resources.Extensions
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.7\System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.7\System.Drawing.dll
----------------------------------------
ComparePlugin
    アセンブリ バージョン: 1.7.0.0
    場所: C:\ServUO\Tools\UOFiddler\plugins\ComparePlugin.dll
----------------------------------------
System.Windows.Forms.Design
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.7\System.Windows.Forms.Design.dll
----------------------------------------
MassImport
    アセンブリ バージョン: 1.1.0.0
    場所: C:\ServUO\Tools\UOFiddler\plugins\MassImport.dll
----------------------------------------
MultiEditor
    アセンブリ バージョン: 1.5.0.0
    場所: C:\ServUO\Tools\UOFiddler\plugins\MultiEditor.dll
----------------------------------------
SendItem
    アセンブリ バージョン: 1.0.1.0
    場所: C:\ServUO\Tools\UOFiddler\plugins\SendItem.dll
----------------------------------------
System.Buffers
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Buffers.dll
----------------------------------------
System.Resources.Writer
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Resources.Writer.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
TestPlugin
    アセンブリ バージョン: 1.0.0.0
    場所: C:\ServUO\Tools\UOFiddler\plugins\TestPlugin.dll
----------------------------------------
UOPPacker
    アセンブリ バージョン: 1.1.1.0
    場所: C:\ServUO\Tools\UOFiddler\plugins\UOPPacker.dll
----------------------------------------
mscorlib
    アセンブリ バージョン: 4.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\mscorlib.dll
----------------------------------------
System.Diagnostics.StackTrace
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    アセンブリ バージョン: 8.0.0.0
    場所: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\System.Collections.Immutable.dll
----------------------------------------

************** JIT デバッグ **************



```

**Comment by AsYlum-** [comment]
related: https://github.com/polserver/UOFiddler/issues/123 It's due to last update

**Comment by AsYlum-** [comment]
@craymaru partial support for compressed clilocs was added in https://github.com/polserver/UOFiddler/releases/tag/4.15.2 Rest is still work in progress.

**Comment by AsYlum-** [comment]
@craymaru you can now read the NL compressed gumps if you upgrade to latest version https://github.com/polserver/UOFiddler/releases/tag/4.16.1
