### ISSUE TITLE
unhandled exceptions

### ISSUE THREAD

**Issue by MichaelTen** [polserver/UOFiddler#129]
I am seeing quite a few "unhandled exception [...]" errors when navigating between UO Fiddler tabs. I can click continue and it seems to keep letting me view stuff without crashing.. but maybe this should be resolved? i tried to add a screenshot..... 

![image](https://github.com/user-attachments/assets/ffef283e-3b20-4733-894e-de69f1f14138)

>--- ## ## ## ## Top part of Error is a follows.... 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at Ultima.Gumps.GetGump(Int32 index, Boolean& patched)
   at UoFiddler.Controls.UserControls.GumpControl.ListBox_DrawItem(Object sender, DrawItemEventArgs e)
   at System.Windows.Forms.ListBox.WmReflectDrawItem(Message& m)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

************** Loaded Assemblies **************

**Comment by MichaelTen** [comment]
and after 7 or 10 of those... and i kept clicking continue. UO Fiddler finally crash. 

unlimited fun. 🌞🐉🐅💯🧙‍♂️

**Comment by AsYlum-** [comment]
It's because NL patch 7.0.104 introduced new format for gumps and clilocs which is not yet supported in uofiddler.
related:
https://github.com/polserver/UOFiddler/issues/123
https://github.com/polserver/UOFiddler/issues/124
