### ISSUE TITLE
Crash on Map tab

### ISSUE THREAD

**Issue by AsYlum-** [polserver/UOFiddler#13]
When you click Preload Map on Map tab and try to drag displayed map the application will crash.

Stack trace:

>    at System.IO.__Error.FileNotOpen()
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at Ultima.TileMatrix.ReadLandBlock(Int32 x, Int32 y) in F:\Dev\UOFiddler\Ultima\TileMatrix.cs:line 559
   at Ultima.TileMatrix.GetLandBlock(Int32 x, Int32 y, Boolean patch) in F:\Dev\UOFiddler\Ultima\TileMatrix.cs:line 252
   at Ultima.Map.RenderBlock(Int32 x, Int32 y, Boolean drawStatics, Boolean diff) in F:\Dev\UOFiddler\Ultima\Map.cs:line 343
   at Ultima.Map.GetRenderedBlock(Int32 x, Int32 y, Boolean statics) in F:\Dev\UOFiddler\Ultima\Map.cs:line 333
   at Ultima.Map.GetImage(Int32 x, Int32 y, Int32 width, Int32 height, Bitmap bmp, Boolean statics) in F:\Dev\UOFiddler\Ultima\Map.cs:line 520
   at Ultima.Map.GetImage(Int32 x, Int32 y, Int32 width, Int32 height, Boolean statics) in F:\Dev\UOFiddler\Ultima\Map.cs:line 151
   at UoFiddler.Controls.UserControls.Map.OnPaint(Object sender, PaintEventArgs e) in F:\Dev\UOFiddler\UoFiddler.Controls\UserControls\Map.cs:line 532
   at System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.PictureBox.OnPaint(PaintEventArgs pe)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Admin-Yukiko** [comment]
I don't know why but I cannot reproduce this issue. I tried both dragging while the map was loading and dragging after the load was finished. I did build for x64. That might make a difference.

**Comment by AsYlum-** [comment]
Fixed.
