### ISSUE TITLE
Exporting from Gumps tab is exporting Texture art?

### ISSUE THREAD

**Issue by Slegnor** [polserver/UOFiddler#35]
Bit of an odd one I've encountered, and sorry for the long post, when I started writing this report, i thought it was just an exception issue but then it got weirder...

Version 4.9.1

If I try and export a gump from the following ranges, i get an exception.
0x7 (7) to 0x8 (8)
0x3F (63) to 0x44 (68)
0x4D (77) to 0x70 (112)
0x868 (2152) to 0x9AA (2474)
0xBB8 (3000) to 0xFC5 (4037)
0x4E20 (20000) to 0xEFFF (61183) (this one is from 0x4e20 to the end of the gump list)
(There could be others but that's a lot of gumps to try individually exporting!)

At first I thought it was a gump file problem but then I checked my export folder

the weird bit:
For all the successful exports there is a file there, but its not the gump art, its a texture file but named Gump #.bmp 
IE export Gump 0x1 (the Status box) get texture 0x1 (the pink square) file named Gump 1.bmp

The export exceptions seem to occur when there's no texture tile with the same ID as the gump (ie gump 0xA9B (2715) exists but texture 0xA9B doesn't)

Things I've tried:
1) Export with Fiddler 4.6 - listed ranges all work and export the correct gump image as normal.
2) Got another 4.9.1 user to export with 4.9.1 on their system - same issue on the listed gump ranges.
3) Tried with vanilla UO muls and another shards modified gump mul/idx files - same issue.
4) Moved Fiddler folder out of Dropbox to my C root incase it was something to do with that, no change
5) Delete all xml files out of  Roaming/UoFiddler and relaunch - xmls recreated but no change.

Exception as follows:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Drawing.Bitmap..ctor(Image original)
   at UoFiddler.Controls.UserControls.Gump.ExportGumpImage(Int32 index, ImageFormat imageFormat)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
UoFiddler
    Assembly Version: 4.9.1.0
    Win32 Version: 4.9.1
    CodeBase: file:///D:/My%20Documents/Dropbox/!Mytharria/UOFiddler/UOFiddler4.9.1/UoFiddler.exe
----------------------------------------
Serilog
    Assembly Version: 2.0.0.0
    Win32 Version: 2.9.0.0
    CodeBase: file:///D:/My%20Documents/Dropbox/!Mytharria/UOFiddler/UOFiddler4.9.1/Serilog.DLL
----------------------------------------
Serilog.Sinks.File
    Assembly Version: 2.0.0.0
    Win32 Version: 4.1.0.0
    CodeBase: file:///D:/My%20Documents/Dropbox/!Mytharria/UOFiddler/UOFiddler4.9.1/Serilog.Sinks.File.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Controls
    Assembly Version: 4.4.0.0
    Win32 Version: 4.4.0
    CodeBase: file:///D:/My%20Documents/Dropbox/!Mytharria/UOFiddler/UOFiddler4.9.1/Controls.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Ultima
    Assembly Version: 4.3.2.0
    Win32 Version: 4.3.2
    CodeBase: file:///D:/My%20Documents/Dropbox/!Mytharria/UOFiddler/UOFiddler4.9.1/Ultima.DLL
----------------------------------------
Octokit
    Assembly Version: 0.46.0.0
    Win32 Version: 0.46.0.0
    CodeBase: file:///D:/My%20Documents/Dropbox/!Mytharria/UOFiddler/UOFiddler4.9.1/Octokit.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
ComparePlugin
    Assembly Version: 1.7.0.0
    Win32 Version: 1.7.0.0
    CodeBase: file:///D:/My%20Documents/Dropbox/!Mytharria/UOFiddler/UOFiddler4.9.1/plugins/ComparePlugin.dll
----------------------------------------
MassImport
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///D:/My%20Documents/Dropbox/!Mytharria/UOFiddler/UOFiddler4.9.1/plugins/MassImport.dll
----------------------------------------
MultiEditor
    Assembly Version: 1.5.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///D:/My%20Documents/Dropbox/!Mytharria/UOFiddler/UOFiddler4.9.1/plugins/MultiEditor.dll
----------------------------------------
SendItem
    Assembly Version: 1.0.1.0
    Win32 Version: 1.0.1.0
    CodeBase: file:///D:/My%20Documents/Dropbox/!Mytharria/UOFiddler/UOFiddler4.9.1/plugins/SendItem.dll
----------------------------------------
TestPlugin
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/My%20Documents/Dropbox/!Mytharria/UOFiddler/UOFiddler4.9.1/plugins/TestPlugin.dll
----------------------------------------
UOPPacker
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0
    CodeBase: file:///D:/My%20Documents/Dropbox/!Mytharria/UOFiddler/UOFiddler4.9.1/plugins/UOPPacker.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```
_edit: by AsYlum: fixed formatting._

**Comment by AsYlum-** [comment]
That was fixed in latest pre-release. Just download it again.

**Comment by Slegnor** [comment]
Crap, I checked the commits before I posted, must have missed it

"Fix gump export option. "

**Comment by AsYlum-** [comment]
Because 4.9.1 needs some more fixes I'm still holding it as pre-release that I'm constantly updating. So some confusion is expected. Sorry about that. In next few weeks I will try to add description about current project state.

**Comment by Slegnor** [comment]
Its OK, you did include it in the changelog, I just missed it
