### ISSUE TITLE
Animation Tab Unhandled Exception - "Index was outside the bounds of the array"

### ISSUE THREAD

**Issue by HellRayzor** [polserver/UOFiddler#90]
When selecting the "Animations" tab UOFiddler throws an unhandled exception error, "index was outside the bounds pf the array".  This is with a fresh compile from the code on Github.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at UoFiddler.Controls.UserControls.AnimationListControl.LoadXml() in C:\UOFiddler-master\UoFiddler.Controls\UserControls\AnimationListControl.cs:line 630
   at UoFiddler.Controls.UserControls.AnimationListControl.OnLoad(Object sender, EventArgs e) in C:\UOFiddler-master\UoFiddler.Controls\UserControls\AnimationListControl.cs:line 187
   at System.Windows.Forms.UserControl.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.TabPage.set_Visible(Boolean value)
   at System.Windows.Forms.TabControl.UpdateTabSelection(Boolean updateFocus)
   at System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
UoFiddler
    Assembly Version: 4.9.8.0
    Win32 Version: 4.9.8
    CodeBase: file:///C:/UOFiddler-master/UoFiddler/bin/Debug/UoFiddler.exe
----------------------------------------
Serilog
    Assembly Version: 2.0.0.0
    Win32 Version: 2.10.0.0
    CodeBase: file:///C:/UOFiddler-master/UoFiddler/bin/Debug/Serilog.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Serilog.Sinks.File
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.0.0
    CodeBase: file:///C:/UOFiddler-master/UoFiddler/bin/Debug/Serilog.Sinks.File.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Controls
    Assembly Version: 4.4.0.0
    Win32 Version: 4.4.0
    CodeBase: file:///C:/UOFiddler-master/UoFiddler/bin/Debug/Controls.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Ultima
    Assembly Version: 4.3.2.0
    Win32 Version: 4.3.2
    CodeBase: file:///C:/UOFiddler-master/UoFiddler/bin/Debug/Ultima.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///C:/UOFiddler-master/UoFiddler/bin/Debug/System.Resources.Extensions.DLL
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/UOFiddler-master/UoFiddler/bin/Debug/System.Memory.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 4.0.4.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/UOFiddler-master/UoFiddler/bin/Debug/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.4.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/UOFiddler-master/UoFiddler/bin/Debug/System.Numerics.Vectors.DLL
----------------------------------------
ComparePlugin
    Assembly Version: 1.7.0.0
    Win32 Version: 1.7.0.0
    CodeBase: file:///C:/UOFiddler-master/UoFiddler/bin/Debug/plugins/ComparePlugin.dll
----------------------------------------
Controls
    Assembly Version: 4.4.0.0
    Win32 Version: 4.4.0
    CodeBase: file:///C:/UOFiddler-master/UoFiddler/bin/Debug/plugins/Controls.dll
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
MassImport
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/UOFiddler-master/UoFiddler/bin/Debug/plugins/MassImport.dll
----------------------------------------
MultiEditor
    Assembly Version: 1.5.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///C:/UOFiddler-master/UoFiddler/bin/Debug/plugins/MultiEditor.dll
----------------------------------------
SendItem
    Assembly Version: 1.0.1.0
    Win32 Version: 1.0.1.0
    CodeBase: file:///C:/UOFiddler-master/UoFiddler/bin/Debug/plugins/SendItem.dll
----------------------------------------
Serilog
    Assembly Version: 2.0.0.0
    Win32 Version: 2.10.0.0
    CodeBase: file:///C:/UOFiddler-master/UoFiddler/bin/Debug/plugins/Serilog.dll
----------------------------------------
System.Buffers
    Assembly Version: 4.0.3.0
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/UOFiddler-master/UoFiddler/bin/Debug/plugins/System.Buffers.dll
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/UOFiddler-master/UoFiddler/bin/Debug/plugins/System.Memory.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.4.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/UOFiddler-master/UoFiddler/bin/Debug/plugins/System.Numerics.Vectors.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///C:/UOFiddler-master/UoFiddler/bin/Debug/plugins/System.Resources.Extensions.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 4.0.4.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/UOFiddler-master/UoFiddler/bin/Debug/plugins/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
TestPlugin
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/UOFiddler-master/UoFiddler/bin/Debug/plugins/TestPlugin.dll
----------------------------------------
Ultima
    Assembly Version: 4.3.2.0
    Win32 Version: 4.3.2
    CodeBase: file:///C:/UOFiddler-master/UoFiddler/bin/Debug/plugins/Ultima.dll
----------------------------------------
UOPPacker
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0
    CodeBase: file:///C:/UOFiddler-master/UoFiddler/bin/Debug/plugins/UOPPacker.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by AsYlum-** [comment]
Note to self: problem was with ``type`` attribute in animationlist.xml. It may be a bug in "Try to find new graphics" window. Also we need some validation here to prevent UOFiddler from failing.

**Comment by AsYlum-** [comment]
Added aditional checks for malformed animationlist.xml values. Will skip entries and produce summary about issues.
